# Generated by Django 4.2.3 on 2023-10-15 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carModels", "0002_rename_type_carmodels_car_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carmodels", old_name="company", new_name="car_company",
        ),
        migrations.RenameField(
            model_name="carmodels", old_name="trims", new_name="car_trim",
        ),
    ]
