# Generated by Django 4.2.3 on 2023-10-15 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("carModels", "0003_rename_company_carmodels_car_company_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carmodels", options={"ordering": ["-model_created"]},
        ),
        migrations.AddField(
            model_name="carmodels",
            name="model_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carmodels",
            name="model_poster",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Uploader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carModels.carmodels",
                    ),
                ),
            ],
        ),
    ]
