# Generated by Django 4.2.3 on 2023-10-14 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Companies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("street", models.CharField(blank=True, max_length=400)),
                ("city", models.CharField(blank=True, max_length=400)),
                ("state", models.CharField(blank=True, max_length=2, null=True)),
                ("zip_code", models.IntegerField(blank=True, default=0)),
                ("website", models.URLField(blank=True, max_length=420)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\1?\\d{9,10}$"
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "logo_image",
                    models.ImageField(
                        blank=True,
                        default="companyImages/company.jpeg",
                        upload_to="companyImages",
                    ),
                ),
            ],
        ),
    ]
