# Generated by Django 4.2.3 on 2023-10-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarTrims",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trim_name", models.CharField(max_length=200)),
                ("trim_price", models.DecimalField(decimal_places=4, max_digits=15)),
                ("trim_image", models.ImageField(blank=True, upload_to="trimImages")),
            ],
        ),
    ]
